---
- hosts: all
  vars: 
  tasks:
    - name: Puppet run to get foreman_scap_client config
      shell: puppet agent -t

    - name: get profile
      shell: "grep -A5 '{{ policy_id }}': /etc/foreman_scap_client/config.yaml| grep profile | awk '{print $2}'| sed -e 's/^[ \t]*//'"
      register: profile_contents

    - name: Install openscap-utils
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide

    - name: remediate openscap
      shell: "oscap xccdf eval  --fetch-remote-resources  --remediate --profile '{{ profile_contents.stdout }}' /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"

    - name: Remove contents file
      file:
       path: /tmp/content
       state: absent

    - name: Update Satellite compliance results
      shell: foreman_scap_client '{{ policy_id }}'

